### PR TITLE
Update to recent version from upstream

### PR DESCRIPTION
**Pull request by jenschude**
I also added the check in the HandlebarsHelper for the execute method as you don't have a defined interface

### CODE REVIEW

**Comment by beequeue** [comment]
Hi @jayS-de - thanks for raising this request.  We've currently got someone looking at switching to using your upstream project following your recent updates and addition of support for Symfony 2.  I'm going to hold off on this merge until we determine if we can use your project directly, and direct our QA effort at that.

**Comment by jenschude** [comment]
The biggest issue is, that you are not using the helperInterface or have defined any Interface for it at all. So this may be a step in between a complete change.

**Comment by jenschude** [comment]
Btw it should be possible to write you own helper service class and just set the handlebars.helper_service.class parameter in your application parameters.yml.

**Comment by jenschude** [comment]
@beequeue just released 0.10 of the HandlebarsBundle

The HandlebarsHelper has been renamed to HandlebarsHelperService and implements now a HandlebarsHelperServiceInterface

So it should be easier develop an own helper service and overwrite the builtin one.

Additionally now all the helpers delivered with the HandlebarsBundle are no more registered by default. To add them you could register them in you app services.yml like this:

``` yaml
services:
  app.handlebars.cms:
    parent: handlebars.helper.cms
    tags:
      - { name: handlebars.helper, id: cms }
  app.handlebars.trans:
    parent: handlebars.helper.trans
    tags:
      - { name: handlebars.helper, id: i18n }
  app.handlebars.json:
    parent: handlebars.helper.json
    tags:
      - { name: handlebars.helper, id: json }
```

**Comment by jenschude** [comment]
Closing this PR to get rid of it in my list. If there is still interest I can reopen it

**Pull request closed without merging**
